#!/bin/bash

# Near Countdown - macOS DMG Build Script
# Builds a release version and packages it into a DMG file

set -e

APP_NAME="Near"
BUNDLE_IDENTIFIER="com.near.countdown"
BUILD_DIR=".build/release"
DMG_DIR="dist"
VERSION=$(date +%Y%m%d)

echo "🚀 Building Near Countdown for macOS..."

# 1. Build release
echo "📦 Building release..."
swift build -c release

# 2. Create app bundle structure
echo "📁 Creating app bundle..."
APP_BUNDLE="$DMG_DIR/$APP_NAME.app"
rm -rf "$DMG_DIR"
mkdir -p "$APP_BUNDLE/Contents/MacOS"
mkdir -p "$APP_BUNDLE/Contents/Resources"
mkdir -p "$APP_BUNDLE/Contents/Frameworks"

# 3. Copy executable
cp "$BUILD_DIR/NearCountdown" "$APP_BUNDLE/Contents/MacOS/$APP_NAME"

# 3.1 Copy Frameworks (CRITICAL for Dynamic Libraries like Lottie)
echo "📦 Copying Frameworks..."
# Use -L to follow symbolic links like .build/release
find -L .build/release -name "*.framework" -type d -exec cp -R {} "$APP_BUNDLE/Contents/Frameworks/" \;

# 4. Copy resources
if [ -d "Resources" ]; then
    cp -r Resources/* "$APP_BUNDLE/Contents/Resources/"
fi

# 4.1 Copy SwiftPM Resources Bundle (CRITICAL)
# Find the .bundle directory generated by SwiftPM
# Use -L to follow symbolic links like .build/release
BUNDLE_PATH=$(find -L .build/release -name "*.bundle" -type d | head -n 1)
if [ -n "$BUNDLE_PATH" ]; then
    echo "📦 Copying resources bundle: $BUNDLE_PATH"
    cp -r "$BUNDLE_PATH" "$APP_BUNDLE/Contents/Resources/"
fi

# 5. Create Info.plist
cat > "$APP_BUNDLE/Contents/Info.plist" << EOF
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>CFBundleName</key>
    <string>$APP_NAME</string>
    <key>CFBundleDisplayName</key>
    <string>$APP_NAME</string>
    <key>CFBundleIdentifier</key>
    <string>$BUNDLE_IDENTIFIER</string>
    <key>CFBundleVersion</key>
    <string>$VERSION</string>
    <key>CFBundleShortVersionString</key>
    <string>1.0.0</string>
    <key>CFBundlePackageType</key>
    <string>APPL</string>
    <key>CFBundleExecutable</key>
    <string>$APP_NAME</string>
    <key>CFBundleIconFile</key>
    <string>AppIcon.icns</string>
    <key>LSMinimumSystemVersion</key>
    <string>12.0</string>
    <key>LSUIElement</key>
    <true/>
    <key>NSHighResolutionCapable</key>
    <true/>
    <key>NSSupportsAutomaticGraphicsSwitching</key>
    <true/>
</dict>
</plist>
EOF

# 5.1 Fix RPATH (CRITICAL for dynamic libraries in bundles)
echo "🔗 Fixing RPATH..."
install_name_tool -add_rpath "@executable_path/../Frameworks" "$APP_BUNDLE/Contents/MacOS/$APP_NAME" || true

# 5.2 Clean Extended Attributes (IMPORTANT)
# Prevents "App is damaged" errors due to quarantine flags
echo "🧹 Cleaning extended attributes..."
xattr -cr "$APP_BUNDLE"

# 5.3 Add Ad-hoc Code Signing (CRITICAL for macOS 12+)
# Use explicit recursive signing for reliability
echo "✍️  Signing application..."
if [ -d "$APP_BUNDLE/Contents/Frameworks" ]; then
    find "$APP_BUNDLE/Contents/Frameworks" -type f -name "*.dylib" -or -name "*.framework" | while read -r lib; do
        codesign --force --sign - "$lib"
    done
fi
codesign --force --sign - "$APP_BUNDLE"

# 6. Create DMG
echo "💿 Creating DMG..."
DMG_NAME="$APP_NAME-$VERSION.dmg"
DMG_PATH="$DMG_DIR/$DMG_NAME"

# Create temporary DMG directory
TEMP_DMG_DIR="$DMG_DIR/dmg_temp"
mkdir -p "$TEMP_DMG_DIR"
cp -r "$APP_BUNDLE" "$TEMP_DMG_DIR/"

# Create symbolic link to Applications folder
ln -s /Applications "$TEMP_DMG_DIR/Applications"

# Create DMG
hdiutil create -volname "$APP_NAME" \
    -srcfolder "$TEMP_DMG_DIR" \
    -ov -format UDZO \
    "$DMG_PATH"

# Cleanup
rm -rf "$TEMP_DMG_DIR"

echo ""
echo "✅ Build complete!"
echo "📦 App Bundle: $APP_BUNDLE"
echo "💿 DMG: $DMG_PATH"
echo ""
echo "To install: Open the DMG and drag Near to /Applications folder."
echo "⚠️  IMPORTANT: If the app fails to open after a reboot, run this command in Terminal:"
echo "   xattr -cr /Applications/Near.app"
